name: secure_chat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  http: ^1.3.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.5
  intl: ^0.18.0
  pointycastle: ^3.4.0
  basic_utils: ^5.7.0
  flutter_secure_storage: ^9.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/undraw_mobile-encryption_flk2.svg
    - assets/default1.png
    - assets/default2.png
    - assets/default3.png
    - assets/default4.png
